name: Deploy Frontend to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 74.234.195.22
          username: azureuser
          key: ${{ secrets.VMKEY }}
          script: |
            cd movies-frontend
            git pull
            npm install
            npm run build
            pm2 delete movies-frontend || true
            pm2 start npm --name "movies-frontend" -- run start
            pm2 save
