name: Deploy Frontend to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 74.234.195.22
          username: azureuser
          key: ${{ secrets.VMKEY }}
          script: |
            cd movie-front
            git pull
            npm install
            pm2 restart movies-frontend
